# Generated by Django 6.0.3 on 2026-03-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipe_category_recipe_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('new_years', "New Year's"), ('mothers_day', "Mother's Day"), ('keto', 'Keto'), ('vegetarian', 'Vegetarian')], max_length=20, null=True),
        ),
    ]
